# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paramDialog.ui'
#
# Created: Mon Apr 20 14:05:47 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_paramsDialog(object):
    def setupUi(self, paramsDialog):
        paramsDialog.setObjectName(_fromUtf8("paramsDialog"))
        paramsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        paramsDialog.resize(464, 550)
        paramsDialog.setMaximumSize(QtCore.QSize(464, 550))
        paramsDialog.setAcceptDrops(True)
        self.buttonBox = QtGui.QDialogButtonBox(paramsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 510, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.missingLine = QtGui.QLineEdit(paramsDialog)
        self.missingLine.setGeometry(QtCore.QRect(360, 60, 91, 29))
        self.missingLine.setMaxLength(10)
        self.missingLine.setObjectName(_fromUtf8("missingLine"))
        self.label_3 = QtGui.QLabel(paramsDialog)
        self.label_3.setGeometry(QtCore.QRect(8, 60, 241, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(paramsDialog)
        self.label_4.setGeometry(QtCore.QRect(8, 90, 241, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.toleranceLine = QtGui.QLineEdit(paramsDialog)
        self.toleranceLine.setGeometry(QtCore.QRect(360, 90, 91, 29))
        self.toleranceLine.setMaxLength(10)
        self.toleranceLine.setObjectName(_fromUtf8("toleranceLine"))
        self.pvalueLine = QtGui.QLineEdit(paramsDialog)
        self.pvalueLine.setGeometry(QtCore.QRect(360, 120, 91, 29))
        self.pvalueLine.setMaxLength(10)
        self.pvalueLine.setObjectName(_fromUtf8("pvalueLine"))
        self.label_5 = QtGui.QLabel(paramsDialog)
        self.label_5.setGeometry(QtCore.QRect(8, 120, 351, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(paramsDialog)
        self.label_6.setGeometry(QtCore.QRect(8, 150, 341, 41))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.unexpGenotypeLine = QtGui.QLineEdit(paramsDialog)
        self.unexpGenotypeLine.setGeometry(QtCore.QRect(360, 160, 91, 29))
        self.unexpGenotypeLine.setMaxLength(10)
        self.unexpGenotypeLine.setObjectName(_fromUtf8("unexpGenotypeLine"))
        self.label_7 = QtGui.QLabel(paramsDialog)
        self.label_7.setGeometry(QtCore.QRect(8, 20, 221, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.populationCombo = QtGui.QComboBox(paramsDialog)
        self.populationCombo.setGeometry(QtCore.QRect(228, 20, 221, 30))
        self.populationCombo.setObjectName(_fromUtf8("populationCombo"))
        self.populationCombo.addItem(_fromUtf8(""))
        self.populationCombo.addItem(_fromUtf8(""))
        self.populationCombo.addItem(_fromUtf8(""))
        self.populationCombo.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(paramsDialog)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 91, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.parentsCombo = QtGui.QComboBox(paramsDialog)
        self.parentsCombo.setGeometry(QtCore.QRect(100, 290, 351, 30))
        self.parentsCombo.setObjectName(_fromUtf8("parentsCombo"))
        self.label_10 = QtGui.QLabel(paramsDialog)
        self.label_10.setGeometry(QtCore.QRect(8, 330, 101, 41))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.outcrossList = QtGui.QListWidget(paramsDialog)
        self.outcrossList.setGeometry(QtCore.QRect(115, 330, 341, 101))
        self.outcrossList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.outcrossList.setObjectName(_fromUtf8("outcrossList"))
        self.label_11 = QtGui.QLabel(paramsDialog)
        self.label_11.setGeometry(QtCore.QRect(8, 440, 361, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.chrLine = QtGui.QLineEdit(paramsDialog)
        self.chrLine.setGeometry(QtCore.QRect(390, 440, 61, 29))
        self.chrLine.setMaxLength(6)
        self.chrLine.setObjectName(_fromUtf8("chrLine"))
        self.label_12 = QtGui.QLabel(paramsDialog)
        self.label_12.setGeometry(QtCore.QRect(10, 470, 211, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.nullAlleleCombo = QtGui.QComboBox(paramsDialog)
        self.nullAlleleCombo.setGeometry(QtCore.QRect(230, 470, 221, 30))
        self.nullAlleleCombo.setObjectName(_fromUtf8("nullAlleleCombo"))
        self.nullAlleleCombo.addItem(_fromUtf8(""))
        self.nullAlleleCombo.addItem(_fromUtf8(""))
        self.rareLine = QtGui.QLineEdit(paramsDialog)
        self.rareLine.setEnabled(False)
        self.rareLine.setGeometry(QtCore.QRect(360, 250, 91, 29))
        self.rareLine.setMaxLength(10)
        self.rareLine.setObjectName(_fromUtf8("rareLine"))
        self.label_9 = QtGui.QLabel(paramsDialog)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(8, 250, 351, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.unexpGenotypeLine_snp = QtGui.QLineEdit(paramsDialog)
        self.unexpGenotypeLine_snp.setGeometry(QtCore.QRect(360, 210, 91, 29))
        self.unexpGenotypeLine_snp.setMaxLength(10)
        self.unexpGenotypeLine_snp.setObjectName(_fromUtf8("unexpGenotypeLine_snp"))
        self.label_13 = QtGui.QLabel(paramsDialog)
        self.label_13.setGeometry(QtCore.QRect(8, 200, 341, 41))
        self.label_13.setObjectName(_fromUtf8("label_13"))

        self.retranslateUi(paramsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), paramsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), paramsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(paramsDialog)

    def retranslateUi(self, paramsDialog):
        paramsDialog.setWindowTitle(QtGui.QApplication.translate("paramsDialog", "Set Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.missingLine.setText(QtGui.QApplication.translate("paramsDialog", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("paramsDialog", " Allowed missing data (range [0,1])", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("paramsDialog", "Call Rate tolerance (range [0,1])", None, QtGui.QApplication.UnicodeUTF8))
        self.toleranceLine.setText(QtGui.QApplication.translate("paramsDialog", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.pvalueLine.setText(QtGui.QApplication.translate("paramsDialog", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("paramsDialog", "p-Value (Chi-sq) segregation distortion (range [0,1])", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("paramsDialog", "Unexpected genotype threshold per individual \n"
"(range [0,1])", None, QtGui.QApplication.UnicodeUTF8))
        self.unexpGenotypeLine.setText(QtGui.QApplication.translate("paramsDialog", "0.003", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("paramsDialog", "Population type", None, QtGui.QApplication.UnicodeUTF8))
        self.populationCombo.setItemText(0, QtGui.QApplication.translate("paramsDialog", "CP (F1)", None, QtGui.QApplication.UnicodeUTF8))
        self.populationCombo.setItemText(1, QtGui.QApplication.translate("paramsDialog", "BC", None, QtGui.QApplication.UnicodeUTF8))
        self.populationCombo.setItemText(2, QtGui.QApplication.translate("paramsDialog", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.populationCombo.setItemText(3, QtGui.QApplication.translate("paramsDialog", "Germplasm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("paramsDialog", "Parents", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("paramsDialog", "Individuals to\n"
"exclude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("paramsDialog", "Number of chromosomes", None, QtGui.QApplication.UnicodeUTF8))
        self.chrLine.setText(QtGui.QApplication.translate("paramsDialog", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("paramsDialog", "AB sub-clusters & Null alleles", None, QtGui.QApplication.UnicodeUTF8))
        self.nullAlleleCombo.setItemText(0, QtGui.QApplication.translate("paramsDialog", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.nullAlleleCombo.setItemText(1, QtGui.QApplication.translate("paramsDialog", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.rareLine.setText(QtGui.QApplication.translate("paramsDialog", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("paramsDialog", "Frequency rare allele (range [0,1])", None, QtGui.QApplication.UnicodeUTF8))
        self.unexpGenotypeLine_snp.setText(QtGui.QApplication.translate("paramsDialog", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("paramsDialog", "Unexpected genotype threshold per SNP \n"
"(range [0,1])", None, QtGui.QApplication.UnicodeUTF8))

